return {
	guarduber = {
		acceleration = 0,
		activatewhenbuilt = true,
		autoheal = 0,
		bmcode = "0",
		brakerate = 0,
		buildcostenergy = 1,
		buildcostmetal = 1,
		builder = false,
		buildtime = 1,
		canrepeat = false,
		category = "NOTAIR NOTSUB NOTSHIP ALL SURFACE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "1 1 1",
		collisionvolumetype = "sphere",
		description = "Sneakily spots the enemy for you",
		explodeas = "",
		footprintx = 1,
		footprintz = 1,
		icontype = "special",
		idleautoheal = 0,
		idletime = 0,
		levelground = false,
		mass = 1,
		maxdamage = 2,
		maxvelocity = 0,
		name = "spotter",
		noautofire = false,
		objectname = "Units/Other/meteorite.s3o",
		radardistance = 600,
		seismicsignature = 4,
		selfdestructas = "",
		side = "BOW",
		script="Other/spotter.cob",
		sightdistance = 400,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0,
		turnrate = 0,
		unitname = "Uber Guardian",
		upright = true,
		waterline = 0,
		workertime = 0,
		yardmap = "o",
		customparams = {
			removestop = true,
			removewait = true,
			subfolder = "other",
		},
		featuredefs = {},
		sfxtypes = {
		},
		weapondefs = {
		},
		weapons = {
		},
	},
}
