--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--
--  file:    callins.lua
--  brief:   array and map of call-ins
--  author:  Dave Rodgers
--
--  Copyright (C) 2007.
--  Licensed under the terms of the GNU GPL, v2 or later.
--
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CallInsList = {
  "AddConsoleLine",
  "AllowCommand",
  "AllowFeatureBuildStep",
  "AllowFeatureCreation",
  "AllowResourceLevel",
  "AllowResourceTransfer",
  "AllowUnitBuildStep",
  "AllowUnitCloak",
  "AllowUnitCreation",
  "AllowUnitDecloak",
  "AllowUnitTransfer",
  "AllowUnitTransport",
  "AllowUnitTransportLoad",
  "AllowUnitTransportUnload",
  "CobCallback",
  "CommandFallback",
  "CommandNotify",
  "ConfigureLayout",
  "DownloadFailed",
  "DownloadFinished",
  "DownloadProgress",
  "DownloadQueued",
  "DownloadStarted",
  "DrawAlphaFeaturesLua",
  "DrawAlphaUnitsLua",
  "DrawOpaqueFeaturesLua",
  "DrawOpaqueUnitsLua",
  "DrawShadowFeaturesLua",
  "DrawShadowUnitsLua",  
  "DrawGenesis",
  "DrawGrass",
  "DrawGroundPostForward",
  "DrawGroundPreForward",
  "DrawInMiniMap",
  "DrawScreen",
  "DrawScreenEffects",
  "DrawScreenPost",
  "DrawSky",
  "DrawSun",
  "DrawTrees",
  "DrawWater",  
  "DrawUnit",
  "DrawWorld",
  "DrawWorldPreParticles",  
  "DrawWorldPreUnit",
  "DrawWorldReflection",
  "DrawWorldRefraction",
  "DrawWorldShadow",
  "Explosion",
  "FeatureCreated",
  "FeatureDestroyed",
  "GameFrame",
  "GameLoadLua",  
  "GameOver",
  "GameProgress",  
  "GamePreload",
  "GameStart",
  "GameStartPlaying",
  "GetTooltip",
  "GroupChanged",
  "IsAbove",
  "JoyAxis",
  "JoyButtonDown",
  "JoyButtonUp",
  "JoyHat",
  "KeyPress",
  "KeyRelease",
  "LayoutButtons",
  "MouseMove",
  "MousePress",
  "MouseRelease",
  "MoveCtrlNotify",
  "ProjectileCreated",
  "ProjectileDestroyed",
  "RecvSkirmishAIMessage",
  "RenderUnitDestroyed",
  "Save",
  "ShieldPreDamaged",
  "ShockFront",
  "Shutdown",
  "SunChanged",
  "TeamDied",
  "TextEditing",
  "TextInput",
  "TerraformComplete",
  "UnitCloaked",
  "UnitCommand",
  "UnitCreated",
  "UnitDecloaked",
  "UnitDestroyed",
  "UnitEnteredAir",
  "UnitEnteredLos",
  "UnitEnteredRadar",
  "UnitEnteredWater",
  "UnitFinished",
  "UnitFromFactory",
  "UnitGiven",
  "UnitHarvestStorageFull",  
  "UnitIdle",
  "UnitLeftAir",
  "UnitLeftLos",
  "UnitLeftRadar",
  "UnitLeftWater",
  "UnitLoaded",
  "UnitReverseBuilt",
  "UnitSeismicPing",
  "UnitTaken",
  "UnitUnloaded",
  "UnsyncedHeightMapUpdate",
  "WorldTooltip",
}


-- make the map
CallInsMap = {}
for _, callin in ipairs(CallInsList) do
  CallInsMap[callin] = true
end


--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
