---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Breno.
--- DateTime: 10/30/2023 4:20 AM
---

function gadget:GetInfo()
    return {
        name      = "Unit Avoid Shooting Guardians",
        desc      = "Units won't auto-attack guardians, except if you force-attack them",
        author    = "MaDDoX",
        date      = "October, 2023",
        license   = "GNU GPL, v2 or later",
        layer     = 51,
        enabled   = true
    }
end


-- Synced Part:
if not gadgetHandler:IsSyncedCode() then
    return end

VFS.Include("gamedata/taptools.lua")

local spGetAllUnits = Spring.GetAllUnits
local spGetUnitDefID = Spring.GetUnitDefID
local g_GuardianAttackers
local g_Guardians

function gadget:Initialize()
    g_Guardians = GG.Guardians
    g_GuardianAttackers = GG.GuardianAttackers

    --for _, unitID in ipairs(spGetAllUnits()) do
    --    local unitDefID = spGetUnitDefID(unitID)
    --    gadget:UnitCreated(unitID, unitDefID)
    --end

    for weaponID,wd in pairs(WeaponDefs) do
        --if wd.customParams and wd.customParams.is_unit_weapon then
        Script.SetWatchAllowTarget(weaponID, true)
        --end
    end
end

-- Checks if the guardian can be auto-attacked or not
function gadget:AllowWeaponTarget(unitID, targetID, attackerWeaponNum, attackerWeaponDefID, defPriority)
    --if not (defPriority and attackerWeaponDefID) then
    if not attackerWeaponDefID then
        -- This callin is effectively script.BlockShot but for CommandAI.
        -- The engine will discard target priority information.

        --Spring.Echo("no attacker weapon, returning")
        return true end

    if g_Guardians[targetID] then
        if istable(g_GuardianAttackers[targetID]) and g_GuardianAttackers[targetID][unitID] then
            --Spring.Echo("Attacker found!")
            return true, defPriority
        end
        return false, defPriority
    end
    return true, defPriority --return "targetAllowed, targetPriority"
end

