return {
	neutronhail = {
        areaofeffect = 250,
        avoidfeature = false,
        cegtag = "meteoritetrail",
        collidefriendly = 1,
        craterareaofeffect = 250,
        craterboost = 0,
        cratermult = 0,
        edgeeffectiveness = 0.8,
        explosiongenerator = "custom:genericshellexplosion-meteorite",
        explosionspeed = 999,
        firestarter = 70,
        flighttime = 100,
        name = "neutronhail",
        range = 29999,
        reloadtime = 99,
        smoketrail = 1,
        soundhit = "xplonuk4",
        soundhitwet = "sizzle",
        soundhitwetvolume = 0.5,
        stages = 0,
        startvelocity = 1250,
        turret = 1,
        weaponacceleration = 120,
        weapontimer = 10,
        weaponvelocity = 1200,
        wobble = 0,
        damage = {
            default = 400,
        },
		customParams = { damagetype = "pierce"},
	},
}
