-- meteor_tag

return {
  ["plasma_shot"] = {
    glow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 0,
      water              = false, --true,
      properties = {
        airdrag            = 0.9,
        colormap           = [[1.0 1.0 1.0 0.5  0.5 0.5 0.5 0.05  0.5 0.5 0.5 0.01]],
        directional        = true,
        emitrot            = 0,
        --emitrotspread      = [[20 r-20 r20]],
        emitvector         = [[dir]], ---[[0,1,0]],
        gravity            = [[0, -1.05, 0]],
        numparticles       = 1,
        particlelife       = 12, --1800,
        particlelifespread = 2,
        particlesize       = 7,
        particlesizespread = 1,
        particlespeed      = 22, --18,  ---[[6 i0.95]],
        particlespeedspread = 2,
        animParams         = [[4,1,8]], --x, y, dur
        --rotParams          = [[0, 0, -60 r120]],  --- [[0, 0, -180 r360]], --- [[-60 r120, -30 r60, -180 r360]],
        pos                = [[0, 0, 0]],
        sizegrowth         = [[-0.25 r0.25]],  ---0.21,
        sizemod            = 1.0,
        texture            = [[plasma_ball]], ---[[plasma0029]],
        useairlos          = true,
        alwaysvisible      = true,
      },
    },
    trail = {
      class              = [[CExpGenSpawner]],
      count              = 1,
      nounit             = 1,
      properties = {
        delay              = [[0]],
        dir                = [[dir]],
        explosiongenerator = [[custom:meteor_trail]],
        pos                = [[0, 0, 0]],
      },
    },
  },

  ["meteor_trail"] = {
    usedefaultexplosions = false,
    fire = {
      air = true,
      class = [[CSimpleParticleSystem]],
      count = 1,
      ground = true,
      water = true,
      properties = {
        airdrag = 0.9,
        alwaysvisible = true,
        colormap = [[0.01 0.01 0.01 0.015  0.1 0.1 0.1 0.4  0 0 0 0.01]],
        directional = true,
        emitrot = 0,
        emitrotspread = 5,
        emitvector = [[dir]],
        gravity = [[0, -1.05, 0]],
        numparticles = 1,
        particlelife = 13,
        particlelifespread = 5,
        particlesize = 2, --4,
        particlesizespread = 0.5, --4,
        particlespeed = 20, --25,
        particlespeedspread = 6,
        pos = [[0, 0, 0]],
        --sizegrowth = [[-0.25 r0.25]],  --1.9
        sizemod = 1,
        texture = [[fireball]],
      },
    },
  }

  --{
  --  usedefaultexplosions = false,
  --  glow = {
  --    class              = [[CSimpleParticleSystem]],
  --    count              = 1,
  --    ground             = false,
  --    air                = true,
  --    properties = {
  --      --airdrag            = 0.999,
  --      alwaysvisible      = true,
  --      --colormap           = [[0.75 0.25 0.5 0.1 0.25 0.1 0.05 0.05   0.01 0.01 0.005 0.005]],
  --      directional        = true,
  --      --emitrot            = 0,
  --      --emitrotspread      = 20,
  --      --emitvector         = [[dir]],
  --      --gravity            = [[0, -1, 0]],
  --      numparticles       = 1,
  --      particlelife       = 2,
  --      particlelifespread = 0,
  --      particlesize       = [[4]],
  --      particlesizespread = 0,
  --      particlespeed      = [[20]],
  --      particlespeedspread = 0,
  --      pos                = [[0, 0, 0]],
  --      sizegrowth         = 1,
  --      sizemod            = 1,
  --      texture            = [[plasma0029]],
  --      rotParams  = [[-5, -4, 20]], -- speed, accel, startRot |deg/s, deg/s2, deg|  --r40 (random 0,40)
  --    },
  --  },
  --},


  --["meteor_aim"] = {
  --  usedefaultexplosions = false,
  --  glow = {
  --    class              = [[CSimpleParticleSystem]],
  --    count              = 1,
  --    ground             = true,
  --    unit               = 1,
  --    air                = true,
  --    properties = {
  --      airdrag            = 0.999,
  --      alwaysvisible      = true,
  --      colormap           = [[0.75 0.25 0.1 0.1 0.25 0.1 0.05 0.01   0.01 0.01 0.005 0.001]],
  --      directional        = true,
  --      emitrot            = 0,
  --      emitrotspread      = 20,
  --      emitvector         = [[dir]],
  --      gravity            = [[0, -1, 0]],
  --      numparticles       = [[1]],
  --      particlelife       = [[2]],
  --      particlelifespread = 0,
  --      particlesize       = [[150]],
  --      particlesizespread = 0,
  --      particlespeed      = [[20]],
  --      particlespeedspread = 0,
  --      pos                = [[0, 0, 0]],
  --      sizegrowth         = 1,
  --      sizemod            = 1,
  --      texture            = [[plasma0029]],
  --    },
  --  },
  --  trail = {
  --    class              = [[CExpGenSpawner]],
  --    count              = 1,
  --    nounit             = 1,
  --    properties = {
  --      delay              = [[0]],
  --      dir                = [[dir]],
  --      explosiongenerator = [[custom:meteor_trail]],
  --      pos                = [[0, 0, 0]],
  --    },
  --  },
  --},
  --["meteor_tag"] = {
  --  usedefaultexplosions = false,
  --  fire = {
  --    air                = true,
  --    class              = [[CBitmapMuzzleFlame]],
  --    count              = 1,
  --    ground             = true,
  --    underwater         = 1,
  --    water              = true,
  --    properties = {
  --      alwaysvisible      = true,
  --      colormap           = [[1 1 1 0.01	1 0.5 0 0.01	0 0 0 0.01]],
  --      dir                = [[dir]],
  --      frontoffset        = -0.4,
  --      fronttexture       = [[plasma0029]],
  --      length             = -80,
  --      sidetexture        = [[plasma2]],
  --      size               = 80,
  --      sizegrowth         = 1,
  --      ttl                = 2,
  --    },
	--},
  --  trail = {
  --    class              = [[CExpGenSpawner]],
  --    count              = 1,
  --    nounit             = 1,
  --    properties = {
  --      delay              = [[0]],
  --      dir                = [[dir]],
  --      explosiongenerator = [[custom:meteor_trail]],
  --      pos                = [[0, 0, 0]],
  --    },
  --  },
  --},
  --["meteor_fall"] = {
  --  usedefaultexplosions = false,
  --  glow = {
  --    air                = true,
  --    class              = [[CSimpleParticleSystem]],
  --    count              = 1,
  --    ground             = true,
  --    water              = true,
  --    properties = {
  --      airdrag            = 0.9,
  --      alwaysvisible      = true,
  --      colormap           = [[0.5 0.25 0 0.01	0.4 0.2 0 0.01	0 0 0 0.01]],
  --      directional        = false,
  --      emitrot            = 0,
  --      emitrotspread      = 180,
  --      emitvector         = [[0 0 0]],
  --      gravity            = [[0, 0, 0]],
  --      numparticles       = 1,
  --      particlelife       = 2,
  --      particlelifespread = 0,
  --      particlesize       = [[90]],
  --      particlesizespread = 2,
  --      particlespeed      = 0,
  --      particlespeedspread = 0,
  --      pos                = [[0, 0, 0]],
  --      sizegrowth         = 2,
  --      sizemod            = 1,
  --      texture            = [[plasma0029]],
  --    },
  --  },
  --  fire = {
  --    air                = true,
  --    class              = [[CSimpleParticleSystem]],
  --    count              = 1,
  --    ground             = true,
  --    water              = true,
  --    properties = {
  --      airdrag            = 0.9,
  --      alwaysvisible      = true,
  --      colormap           = [[0.01 0.01 0.01 0.015  0.1 0.1 0.1 0.15  0 0 0 0.01]],
  --      directional        = false,
  --      emitrot            = 0,
  --      emitrotspread      = 180,
  --      emitvector         = [[-1 r2,-1 r2,-1 r2]],
  --      gravity            = [[0, 0, 0]],
  --      numparticles       = 1,
  --      particlelife       = 13,
  --      particlelifespread = 5,
  --      particlesize       = 4,
  --      particlesizespread = 4,
  --      particlespeed      = 0,
  --      particlespeedspread = 5,
  --      pos                = [[0, 0, 0]],
  --      sizegrowth         = 1.9,
  --      sizemod            = 1,
  --      texture            = [[fireball]],
  --    },
  --  },
  --  smoke = {
  --    air                = true,
  --    class              = [[CSimpleParticleSystem]],
  --    count              = 1,
  --    ground             = true,
  --    water              = true,
  --    properties = {
  --      airdrag            = 0.9,
  --      alwaysvisible      = true,
  --      colormap           = [[0.02 0.01 0 0.015  0.2 0.1 0 0.15  0.2 0.1 0 0.25  0.2 0 0 0.25  0 0 0 0.2  0 0 0 0.01]],
  --      directional        = false,
  --      emitrot            = 0,
  --      emitrotspread      = 180,
  --      emitvector         = [[-1 r2,-1 r2,-1 r2]],
  --      gravity            = [[0, 0, 0]],
  --      numparticles       = 1,
  --      particlelife       = 25,
  --      particlelifespread = 10,
  --      particlesize       = 6,
  --      particlesizespread = 6,
  --      particlespeed      = 0,
  --      particlespeedspread = 5,
  --      pos                = [[0, 0, 0]],
  --      sizegrowth         = 1.9,
  --      sizemod            = 1,
  --      texture            = [[smokesmall]],
  --    },
  --  },
  --},
  --  smoke = {
  --    air                = true,
  --    class              = [[CSimpleParticleSystem]],
  --    count              = 1,
  --    ground             = true,
  --    water              = true,
  --    properties = {
  --      airdrag            = 0.95,
  --      alwaysvisible      = true,
  --      colormap           = [[0.02 0.01 0 0.015  0.2 0.1 0 0.15  0.2 0.1 0 0.25  0.2 0 0 0.25  0 0 0 0.2  0 0 0 0.01]],
  --      directional        = true,
  --      emitrot            = 0,
  --      emitrotspread      = 5,
  --      emitvector         = [[dir]],
  --      gravity            = [[0, 0, 0]],
  --      numparticles       = 1,
  --      particlelife       = 25,
  --      particlelifespread = 10,
  --      particlesize       = 6,
  --      particlesizespread = 6,
  --      particlespeed      = 25,
  --      particlespeedspread = 8,
  --      pos                = [[0, 0, 0]],
  --      sizegrowth         = 1.9,
  --      sizemod            = 1,
  --      texture            = [[smokesmall]],
  --    },
  --  },
  --}
}

