return {
    ore_sml =
    {
        description = "Small Ore Chunk",
        blocking = 1,
        category = "vegetation", --?
        crushResistance    = 1000, --only t2 tanks can crush this
        damage = 20000,
        energy = 1,
        featurereclamate = "SMUDGE01",
        footprintx = 1,
        footprintz = 1,
        height = 20,
        hitdensity = 999999,
        indestructible     = false,
        metal = 1,
        object = "ore_sml.s3o",
        reclaimable = 1,
        reclaimTime = 5000,
        mass = 20,
        resurrectable = 0,
        seqnamereclamate = "TREE1RECLAMATE",
        upright = false,
        world = "All Worlds",
        customparams = {
            model_author = "MaDDoX",
            normalmaps = "yes",
            normaltex = "unittextures/ore_normal.tga",
            treeshader = "yes",
        },
        featuredefs = {
            dead = {
                --blocking = true,
                --category = "corpses",
                --collisionvolumeoffsets = "0 -18 1",
                --collisionvolumescales = "50 76 50",
                --collisionvolumetype = "Ell",
                --damage = 184,
                --description = "Solar Collector Wreckage",
                --energy = 0,
                --featuredead = "HEAP",
                --featurereclamate = "SMUDGE01",
                --footprintx = 5,
                --footprintz = 5,
                --height = 20,
                --hitdensity = 100,
                --metal = 75,
                --object = "ARMSOLAR_DEAD",
                --reclaimable = true,
                --seqnamereclamate = "TREE1RECLAMATE",
                --world = "All Worlds",
            },
        },
    },
    ore_lrg =
    {
        description = "Large Ore Chunk",
        blocking = 1,
        category = "vegetation", --?
        crushResistance    = 1000, --only t2 tanks can crush this
        damage = 30000,
        energy = 1,
        featurereclamate = "SMUDGE01",
        footprintx = 2,
        footprintz = 2,
        height = 20,
        hitdensity = 999999,
        indestructible = false,
        metal = 1,
        object = "ore_lrg.s3o",
        reclaimable = 1,
        reclaimTime = 7500,
        mass = 30,
        resurrectable = 0,
        seqnamereclamate = "TREE1RECLAMATE",
        upright = false,
        world = "All Worlds",
        customparams = {
            model_author = "MaDDoX",
            normalmaps = "yes",
            normaltex = "unittextures/ore_normal.tga",
            treeshader = "yes",
        },
        featuredefs = {
            dead = {
                --blocking = true,
                --category = "corpses",
                --collisionvolumeoffsets = "0 -18 1",
                --collisionvolumescales = "50 76 50",
                --collisionvolumetype = "Ell",
                --damage = 184,
                --description = "Solar Collector Wreckage",
                --energy = 0,
                --featuredead = "HEAP",
                --featurereclamate = "SMUDGE01",
                --footprintx = 5,
                --footprintz = 5,
                --height = 20,
                --hitdensity = 100,
                --metal = 75,
                --object = "ARMSOLAR_DEAD",
                --reclaimable = true,
                --seqnamereclamate = "TREE1RECLAMATE",
                --world = "All Worlds",
            },
        },
    },
    ore_moho =
    {
        description = "Moho Ore Chunk",
        blocking = 1,
        category = "vegetation", --?
        crushResistance    = 1000, --only t2 tanks can crush this
        damage = 60000,
        energy = 1,
        featurereclamate = "SMUDGE01",
        footprintx = 2,
        footprintz = 2,
        height = 20,
        hitdensity = 999999,
        indestructible = false,
        metal = 1,
        object = "ore_moho.s3o",
        reclaimable = 1,
        reclaimTime = 15000,
        mass = 60,
        resurrectable = 0,
        seqnamereclamate = "TREE1RECLAMATE",
        upright = false,
        world = "All Worlds",
        customparams = {
            model_author = "MaDDoX",
            normalmaps = "yes",
            normaltex = "unittextures/ore_normal.tga",
            treeshader = "yes",
        },
        featuredefs = {
            dead = {
                --blocking = true,
                --category = "corpses",
                --collisionvolumeoffsets = "0 -18 1",
                --collisionvolumescales = "50 76 50",
                --collisionvolumetype = "Ell",
                --damage = 184,
                --description = "Solar Collector Wreckage",
                --energy = 0,
                --featuredead = "HEAP",
                --featurereclamate = "SMUDGE01",
                --footprintx = 5,
                --footprintz = 5,
                --height = 20,
                --hitdensity = 100,
                --metal = 75,
                --object = "ARMSOLAR_DEAD",
                --reclaimable = true,
                --seqnamereclamate = "TREE1RECLAMATE",
                --world = "All Worlds",
            },
        },
    },
    ore_uber =
    {
        description = "Uber Ore Chunk",
        blocking = 1,
        category = "vegetation", --?
        crushResistance    = 2000,
        damage = 90000,
        energy = 1,
        featurereclamate = "SMUDGE01",
        footprintx = 4,
        footprintz = 4,
        height = 20,
        hitdensity = 999999,
        indestructible = false,
        metal = 1,
        object = "ore_uber.s3o",
        reclaimable = 1,
        reclaimTime = 15000,
        mass = 120,
        resurrectable = 0,
        seqnamereclamate = "TREE1RECLAMATE",
        upright = false,
        world = "All Worlds",
        customparams = {
            model_author = "MaDDoX",
            normalmaps = "yes",
            normaltex = "unittextures/ore_normal.tga",
            treeshader = "yes",
        },
        featuredefs = {
            dead = {
                --blocking = true,
                --category = "corpses",
                --collisionvolumeoffsets = "0 -18 1",
                --collisionvolumescales = "50 76 50",
                --collisionvolumetype = "Ell",
                --damage = 184,
                --description = "Solar Collector Wreckage",
                --energy = 0,
                --featuredead = "HEAP",
                --featurereclamate = "SMUDGE01",
                --footprintx = 5,
                --footprintz = 5,
                --height = 20,
                --hitdensity = 100,
                --metal = 75,
                --object = "ARMSOLAR_DEAD",
                --reclaimable = true,
                --seqnamereclamate = "TREE1RECLAMATE",
                --world = "All Worlds",
            },
        },
    },
}